# Site settings
title_left: ""
title_right: "Muhammad" # default: ""
description: "Personal Blog where I write about things I learn or discover."
keywords: "devops, aws, python, ci-cd, terraform, cloudformation, docker, kubernetes, infrastructure-as-code, automation, backend-development"
url: "//muhammadraza.me" # site url
baseurl: "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover: "" # image uri like logo/cover image for site seo

google_analytics: ""
twitter_username: "muhammad_o7"
comments_enabled: true # if enabled (set to true), please provide your disqus_username
disqus_shortname: ""
postshare_enabled: true

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site
excerpt_separator: ""
# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Muhammad Raza"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

exclude:
  [
    "vendor",
    "gulp",
    "node_modules",
    "bower",
    "bower_components",
    "config.rb",
    "src",
    "Gemfile",
    "Gemfile.lock",
    ".rvmrc",
    ".rbenv-version",
    "package.json",
    "gulpfile.js",
    "README.md",
    "Rakefile",
    "changelog.md",
    "script",
  ]

include: ["tags"]
